### ISSUE TITLE
Redirect Google map to office

### ISSUE THREAD

**Issue by blocksoftware** [blocksoftware/website#11]
use this link: https://www.google.com/maps/place/Block+Software+Inc./@46.2800282,-63.1500548,17z/data=!3m1!4b1!4m6!3m5!1s0x4b5fb3639908eb8f:0x6abe6c93b86698eb!8m2!3d46.2800282!4d-63.1474799!16s%2Fg%2F11wmqkykky?entry=ttu&g_ep=EgoyMDI0MTExOC4wIKXMDSoASAFQAw%3D%3D

**Comment by mmiao122671** [comment]
Replace the link
